### ISSUE TITLE
Knowledge currently stored is lost if the process is interrupted

### ISSUE THREAD

**Issue by pacospace** [AICoE/SrcOpsMetrics#84]
**Describe the bug**
Interrupting the process does not store knowledge currently collected, therefore it is lost.

**To Reproduce**
1. Run `PYTHONPATH=. GITHUB_ACCESS_TOKEN=<acces_token> pipenv run python3 srcopsmetrics/cli.py --repository thoth-station/performance -c -l`
2. Interrupt the collection from the keyboard.

**Expected behavior**
The Pull Requested that are currently collected are stored in pull_requests.json.

**Comment by xtuchyna** [comment]
The problem was in the implementation of the context manager. Now whenever keyboard interruption occurs (cmd + c) or an exception in pygithub module raises, the cached knowledge should be stored.
