### ISSUE TITLE
When to update processed knolwedge?

### ISSUE THREAD

**Issue by xtuchyna** [AICoE/SrcOpsMetrics#96]
## When should we update the processed knowledge?

After we create Knowledge out of analysed repositories, we can visualize statistics for each repository. However, visualization needs yet one step to be working - processing the created knowledge into desired information that will be passed to visualization api.

What comes to mind are two options:

-  flag -p can be added when calling cli. If present, it would specifiy that we want to explicitly create new processed knowledge. The old one will then be removed.
- Storing processed knowledge can be actually part of knowledge creation process (-c).

Or maybe there is a better idea? @pacospace @goern

**Comment by pacospace** [comment]
> * flag -p can be added when calling cli. If present, it would specifiy that we want to explicitly create new processed knowledge. The old one will then be removed.

I see the point and I think being part of the `-c` flag make sense in any case because when we check for new knowledge it will automatically reevaluate processed knowledge and substitute to the old one, which will be removed.

**Comment by xtuchyna** [comment]
yes, being part of the create knowledge process makes sense. I am probably gonna also add an option if user does not want to process information and just collect the knowledge

**Comment by xtuchyna** [comment]
resolved in #94
